basePath: /
host: localhost:8080
info:
  contact:
    email: support@bms-go.local
    name: API Support
  description: REST API sederhana untuk mengelola buku dan daftar favorit pengguna.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Book Management System API
  version: "1.0"
paths: {}
swagger: "2.0"
